### ISSUE TITLE
Config property jqassistant.scan.include.files should support file patterns (e.g. wild cards)

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqassistant#410]
The config option should support file patterns like this one:
```yaml
jqassistant:
  scan:
    include:
      files:
        - "nexusiq:scan-report::*report.json"
```
