### ISSUE TITLE
Bug Report - Excludes only affect files not directories

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqassistant#446]
### Bug Description

When trying to exclude certain files and directories via the following (partial) configuration:
```yaml
jqassistant:
  scan:
    properties:
      file.exclude:
        - /node_modules/**
        - /build/**
```

only the files are not represented in the graph. Directory nodes are still generated.

### Expected Behaviour
Nodes should not be generated for excluded directories or files.
