### ISSUE TITLE
Bug Report - Path of  root directory node contains . at the end when scanning whole project

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqassistant#447]
### Bug Description

When trying to scan a whole project with the following scan configuration:
```yaml
jqassistant:
  scan:
    include:
      files:
        - "."
```

the fileName property of the root directory node in the graph has a value like:
`/home/.../sample-project/.`

### Expected Behaviour
The dot at the end of the fileName value should not be there.
