### ISSUE TITLE
Provide a configuration property that represents the version of the embedded Neo4j database

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqassistant#621]
For using the APOC plugin for the embedded Neo4j database currently the version must be specified explicitly:

```
jqassistant:
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc-core
          classifier: core
          version: 5.23.0
```

As the APOC version has the same lifecycle as the embedded Neo4j version it would be helpful if that could be used as property which is provided by default:

```
jqassistant:
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc-core
          classifier: core
          version: ${jqassistant.store.embedded.neo4j-version}
```
