### ISSUE TITLE
AbstractScannerPlugin properties from yml ignored

### ISSUE THREAD

**Issue by UrbanPi** [jQAssistant/jqassistant#709]
Hi,

properties which I set in the `.jqassistant.yml ` seem to be ignored. Specifically I wanted to set properties for the maven3 and JaCoCo plugin. In the `scan` section of the yml I set the following properties according to the [documentation](https://jqassistant.github.io/jqassistant/current/#_yaml_files):

```
  scan:
    reset: true
    continue-on-error: false
    include:
      files:
       - target/site/jacoco
    properties:
      - jqassistant.plugin.jacoco.filename: SOME_FILE_NAME.xml
      - jqassistant.plugin.jacoco.dirname: jacoco
      - maven3.dependencies.scan: true
 ```
When I turn on DEBUG logging output I can see that the properties are read:

```
[DEBUG] 	jqassistant.scan.properties[0]."jqassistant.plugin.jacoco.filename"=SOME_FILE_NAME.xml
[DEBUG] 	jqassistant.scan.properties[1]."jqassistant.plugin.jacoco.dirname"=jacoco
[DEBUG] 	jqassistant.scan.properties[2]."maven3.dependencies.scan"=true
```
(Also the `include.files:- target/site/jacoco` has an effect)
But later there are messages like this one:
```
[DEBUG] SRCFG00050: jqassistant.scan.properties[0]."jqassistant.plugin.jacoco.filename" in jQAssistant Configuration does not map to any root
```

I inserted some logging messages in the implementation of the maven3 plugin and in the AbstractScannerPlugin. The properties obtained there are always empty. 
I searched for parts of the debug message in the project but could not find it. From internet recherche and looking around in the code I suspect that the issue is related to [SmallRye ConfigMappings](https://smallrye.io/smallrye-config/3.9.1/config/mappings/#maps) which are used in the interface `com.buschmais.jqassistant.core.scanner.api.configuration.Scan` and the other JQAssistant lifecycle interfaces. 

In the future I want to add another property to the maven3 plugin to specify a single POM which should be scanned, but for this the properties functionality should be working. 

Best regards!

**Comment by UrbanPi** [comment]
It was my own fault: properties should be a map and not a list:
```
 properties:
      jqassistant.plugin.jacoco.filename: SOME_FILE_NAME.xml
      jqassistant.plugin.jacoco.dirname: jacoco
      maven3.dependencies.scan: true
```
