### ISSUE TITLE
Plugin configuration in YAML should use a single artifactId instead of a list

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqassistant#727]
A plugin config in a YAML looks like this:

```
plugins:
  - group-id: org.jqassistant.plugin
     artifact-id: jqassistant-jee-plugin
     version: 1.1.0-M1
``` 

Actually the property `artifact-id` is currently modeled as an array of strings, not a single value. This feature had been introduced to ease declaration plugins with same groupId and versions, which more and more becomes the exceptional case.
Therefore the array should be replaced by single value to avoid confusion (e.g. in the context of providing JSON schemas for the jQA configuration)
