### ISSUE TITLE
Multiple errors while performing full Maven scan

### ISSUE THREAD

**Issue by ascheman** [jQAssistant/jqassistant#737]
I currently try to scan the full [Apache Maven](https://maven.apache.org/scm.html) project.

Therefore, I have compiled a list of all respective Maven components and their git repositories:

```yaml
jqassistant:
  plugins:
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.git
      version: 2.1.0
  scan:
    continue-on-error: true 
    include:
      files:
        - core/build-cache
        - core/build-cache/.git
        - core/maven
        - core/maven/.git
        - core/maven-3
        - core/maven-3/.git
...
# and another ~240 lines ...
```

Unfortunately jQA already fails while analyzing one of the first POMs (and has many errors while getting there, see the attached log file: [jqa-scan.log.gz](https://github.com/user-attachments/files/18177794/jqa-scan.log.gz)).
