### ISSUE TITLE
JSON schema generator should support profiles in config files

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqassistant#794]
The config files support profiles which may be activated for Maven and CLI (see https://jqassistant.github.io/jqassistant/snapshot/#_plugin_configuration).
In this case there are additional root nodes in the YAML file having `%` as prefix and the name of the profile:

```
"%custom-profile":
  jqassistant:
    store:
      uri: "bolt://localhost:7687"
```

It shall be checked if JSON schema supports this kind of naming pattern.
