### ISSUE TITLE
More extensive options to configure plugin

### ISSUE THREAD

**Issue by WilliamThimm** [jQAssistant/jqassistant#806]
It would be amazing, if one could define a more comprehensive structure to configure ones own plugin.
For example:

```yaml
jqassistant:
  scan:
    properties:
      jqassistant.plugin.antlr.grammars:
       - grammarFile: '\Logging.g4'
           fileExtension: '.logging'
```

This is an example of the desired configuration for a new plugin, however when calling `getProperties()` the reulting property looks like `"\"jqassistant.plugin.antlr.grammars\"[0].grammarFile"`. This is tedious to parse. 

It would be amazing, if I could define my own structure for the properties to be mapped onto.
