### ISSUE TITLE
Feature: Group/Rule-wise Configuration of Warning/Failure Thresholds

### ISSUE THREAD

**Issue by SebastianWendorf** [jQAssistant/jqassistant#820]
Currently it is possible to define a general severity at which a warning/failure during the jQA analysis should occur. This is done via the `jqassistant.analyze.report.warn-on-severity` and `.fail-on-severity` configuration properties, where a concrete severity value like `MAJOR` can be set.

To allow more fine-tuned configuration possibilities it would be good to override the general thresholds described above with group/rule-wise thresholds.

In addition to the current configuration mode, it should be possible to define the  `warn-on-severity` and  `fail-on-severity` as YAML mappings  with the `"*"` key to set the default value and concrete rule/group names as keys for partial overrides of the default value. The use of wildcards should be allowed for the description of rule names.

**Example:**
```yaml
jqassistant:
  # ...
  analyze:
    report:
      warn-on-severity:
        "*": MAJOR
        "my-important-group": MINOR
        "spring:*": CRITICAL
      fail-on-severity:
        "*": CRITICAL
        "my-important-group": MAJOR
        "spring:*": BLOCKER
```
